
/* Nothing here, just a placeholder*/

/* 20190125 BERG (THIS IS TEST NR 1)*/
ALTER TABLE EXTERNAL_MAPPINGS MODIFY MAP_ID VARCHAR(12) NOT NULL;

UPDATE CUSTOMERS SET CUST_VALUE = '2' WHERE CUST_ID = 12354;
UPDATE CUSTOMERS SET CUST_VALUE = '4' 
WHERE LAST_NAME = BERG;

ALTER TABLE CLIENTS MODIFY CLIENT_NO NUMBERIC(10);
ALTER TABLE ORDERS MODYFIY ORDER_NO,
MAP_ID, CLIENT_PHONE NUMERIC(10);